// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBR9cUnJGXZ_-Jhk3T4-lWfEMYzRjWZky4',
    appId: '1:980045015873:web:16e0239527efe7ff8f4fc0',
    messagingSenderId: '980045015873',
    projectId: 'quizzz-79fa5',
    authDomain: 'quizzz-79fa5.firebaseapp.com',
    storageBucket: 'quizzz-79fa5.firebasestorage.app',
    measurementId: 'G-3DCVQNKBB6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAwn66i6A1rJQNqnzxKFvIB3rgWURZFi84',
    appId: '1:980045015873:android:3cb2b9786ecb7d558f4fc0',
    messagingSenderId: '980045015873',
    projectId: 'quizzz-79fa5',
    storageBucket: 'quizzz-79fa5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCUGBYe5v2Mr3d9SMJ-un9MfqGpOT2GOqI',
    appId: '1:980045015873:ios:1d48983f71f6df308f4fc0',
    messagingSenderId: '980045015873',
    projectId: 'quizzz-79fa5',
    storageBucket: 'quizzz-79fa5.firebasestorage.app',
    iosBundleId: 'com.example.quizzz',
  );
}
